steps:
  # Step 1: Fetch password from Secret Manager and Login to Docker Hub
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        docker login --username=$_DOCKER_USER --password-stdin <<< "$$DOCKER_PASSWORD"
    secretEnv: ['DOCKER_PASSWORD']
  # Step 2: Build the image using main.py and requirements.txt
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t', '$_DOCKER_USER/$_REPO_NAME:${_VERSION}',
      '-t', '$_DOCKER_USER/$_REPO_NAME:latest',
      '.'
    ]
  # Step 3: Push to Docker Hub
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '$_DOCKER_USER/$_REPO_NAME', '--all-tags']

substitutions:
  _DOCKER_USER: 'raghuporumamilla'
  _REPO_NAME: 'rporumamilla'
  _VERSION: 'v1.0.0' # Add a default version name here

availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/docker-hub-password/versions/latest
      env: 'DOCKER_PASSWORD'